### ISSUE TITLE
Need babel transform

### ISSUE THREAD

**Issue by rzyanhao** [mourner/flatbush#23]
When I pack it with webpack, I found that the exported file is not transformed by babel。
Uglifyjs caught an error because of es6 "class":
![image](https://user-images.githubusercontent.com/9431954/52943275-c0e07000-33a7-11e9-8ec6-b950af8ae7cb.png)
![image](https://user-images.githubusercontent.com/9431954/52943557-609dfe00-33a8-11e9-9756-75e2e7d494e8.png)

version: 3.1.1

**Comment by mourner** [comment]
The distributed version gets transformed: https://github.com/mourner/flatbush/blob/master/rollup.config.js#L2

The root issue here is that Webpack uses the `module` entry point for the build, which is wrong. I don't think anything should be fixed on the Flatbush side.

**Comment by rzyanhao** [comment]
https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features

> The distributed version gets transformed: https://github.com/mourner/flatbush/blob/master/rollup.config.js#L2
> 
> The root issue here is that Webpack uses the `module` entry point for the build, which is wrong. I don't think anything should be fixed on the Flatbush side.

I think you are wrong,  you should only use `import` and `export` with pkg.module.  https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features

**Comment by mourner** [comment]
@rzyanhao isn't it a common pattern in libraries to have a ES5 build for CommonJS/browsers and a modern build for `module` consumers? Otherwise users wouldn't be able to take advantage of ES6-specific things like smaller builds or better optimization on modern JS engines. 

I feel like this is a good trade-off, and there are easy workarounds like using `terser` in place of `uglifyjs`, or transpiling on the Webpack end before uglifying. But I may be wrong. @Rich-Harris @RReverser hey friends, any thoughts on this?

**Comment by RReverser** [comment]
I'd agree, I think it's fine and fairly common to ship untranspiled ES6+ by default and let downstream consumers transpile code to the required browser set. This way everyone gets code that works best on their targets. 

At the same time, I know there is still resistance to this approach because including `node_modules` into Babel transforms adds extra overhead.

**Comment by Rich-Harris** [comment]
This is a thorny issue for which there are no hard and fast right answers. But my current preference is for libraries to ship modern JS (i.e. runs in all current evergreen browsers — so things like `class` and `await` but not stuff like decorators, class fields or whatever).

It's possible to write an app completely in modern JavaScript and have it run without Babel unless you need to serve IE11, in which case the best practice is to serve IE users a Babelified version of the (much smaller) modern bundle that everyone else gets.

Bear in mind that 'ES6' is synonymous with 'ES2015'. It's 2019.

**Comment by mourner** [comment]
Thanks! I think I'll continue my approach of shipping ES6 for `module` entry point and ES5 for `main` entry point. Perhaps I should just document this in the readme.
