### ISSUE TITLE
Nested rects, get innermost neighbor first?

### ISSUE THREAD

**Issue by Gregoor** [mourner/flatbush#53]
Hi there,

thanks for the great lib!

I'm using it to do cursor-over detection, where naturally a lot of boxes are nested within each other. Now when I retrieve the next neighbor for any given position I'd want to get the innermost box first.

E.g.:
![image](https://github.com/mourner/flatbush/assets/4051932/2ccda3ca-080b-47fc-ae6b-d979161614d2)

Assuming the red dot is between blue-right and green-right, I'd want to get blue anywhere left of it and green anywhere right from it.

Is that possible / within scope for this lib?

**Comment by mourner** [comment]
Nope, it doesn't track such relations between bounding boxes. I guess you could try retrieving multiple neighbors and then comparing relationships between the results manually — it would return the outermost box first because the distance is 0, and then you'd check any other neighbors whether they are contained within the first one.

**Comment by mourner** [comment]
Alternatively, you could index the boxes as four separate edges, that way you'd get the actual closest edge even if query is inside.

**Comment by Gregoor** [comment]
Ah that second one might work for me, thanks for the idea. The first one unfortunately does not because the number of nested boxes could be pretty much arbitrarily high.

A third approach I've been playing with is ordering the boxes by depth, which seems to give me almost the result I want.

Thanks for getting back to me!
