### ISSUE TITLE
search performance improvement: remove upperBound binary search

### ISSUE THREAD

**Issue by jwass** [mourner/flatbush#6]
Hello, I was looking through the Flatbush code and wondered whether there is some performance to be gained by eliminating the `upperBound` call in `search`. As you build the queue, you can track the current level of each node, or iterate over the tree level by level instead.  Since you’d know the current level, `end` would be an index lookup into `_levelBoundaries` instead of the binary search over it.

I don’t know a lot about Javascript performance nuances, but it seems like that could lead to a significant search performance improvement - at least for larger trees/queries.

Mostly just curious :)

**Comment by mourner** [comment]
Hey Jacob, thanks for the thoughts! I tried to track the level along with the index in the queue (pushing/popping both), but it's surprisingly slightly slower — I guess keeping a 2x bigger queue array offsets any gains. Also, since the level boundaries array is very small (e.g. just 5 for a million items), in practice the binary search is almost instant.

If you find a way to eliminate the upper bound search while improving performance, I'll happily accept a PR!

**Comment by mourner** [comment]
@jwass turns out it was a good idea after all! https://github.com/mourner/flatbush/commit/8720096e89aa43d54e3361a02117717f00ee9996 brings a tiny improvement while removing code. 

Previously, it showed a slowdown because V8 didn't properly detect that the queue only holds small integers. This commit fixed it: https://github.com/mourner/flatbush/commit/5edf164ba2416d1e209cceac6a64d479365575f8

**Comment by jwass** [comment]
That's great! Glad this wasn't a total distraction :)
